# Generated by Django 4.0.4 on 2022-05-07 16:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('receivers', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Receivers',
            new_name='Receiver',
        ),
    ]
