# Generated by Django 4.0.4 on 2022-05-08 12:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invoices', '0002_tag'),
    ]

    operations = [
        migrations.AddField(
            model_name='invoice',
            name='tag',
            field=models.ManyToManyField(blank=True, to='invoices.tag'),
        ),
    ]
