# Generated by Django 4.0.4 on 2022-05-09 14:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('positions', '0002_rename_desciption_position_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='position',
            name='description',
            field=models.TextField(blank=True, help_text='Optional Text'),
        ),
    ]
